Adding [Scala] language
devstrons/heloworld pull request #100
Opened 2022-10-11 16:48 UTC by techysubham

### **Description**
Added Scala Language in ```lang``` folder

**Notes for Reviewers:**

**[Signed commits](https://github.com/devstrons/heloworld/blob/master/CONTRIBUTING.md)**

- [ ] Yes, I am a Member of **DEVSTRONS'**

**Discord ID** (e.g.: DEVSTRONS'#0238)
```AnonymousGeek#9515```

2022-10-11 18:35 UTC, Panquesito7 requested changes
Great work! 🚀

2022-10-11 18:35 UTC, Panquesito7 commented on lang/scala.md
> +- Step 2: Now install Scala
```suggestion
- Step 2: Installing Scala
```

2022-10-11 18:35 UTC, Panquesito7 commented on lang/scala.md
> +
```suggestion
We are done with installing the Java SDK. Now let’s install the Scala packages. The best option to download these packages is to download from the official site only: https://www.scala-lang.org/download/ 
The packages in the link above are approximately 100MB. Once the packages are downloaded, open the downloaded `.msi` file and install it.

- Step 3: Testing and running the Scala Commands
  
Open the command prompt now and type in the following codes:

  `C:\Users\Your_PC_username>scala`
```

2022-10-11 18:35 UTC, Panquesito7 commented on lang/scala.md
> +- BlueJ
Could you please link to their official websites (if applicable)?

2022-10-12 06:31 UTC, techysubham commented
Made necessary changes , please check it.
Cheers...

2022-10-14 13:53 UTC, Panquesito7 requested changes
Please add Wikipedia links when applicable to easily check the sources (like seen below).

2022-10-14 16:37 UTC, techysubham commented
Added the Wikipedia links.
You can verify it.

2022-10-14 17:55 UTC, Panquesito7 requested changes

2022-10-14 17:55 UTC, Panquesito7 commented on lang/scala.md
> +- The first thing we need to have is a Java Software Development Kit(SDK) installed on the computer. We need to verify these SDK packages and if not installed then install them. Open the command wind
Provide a Wikipedia link to the Java SDK. Check other instances where it's needed as well.

2022-10-15 06:11 UTC, techysubham commented
Made the necessary changes.
You can verify it.

2022-10-21 06:46 UTC, aminoxix commented
@techysubham can you pl add some emojis to your document of Scala? Refer to any other lang's docs pushed.

2022-10-21 15:54 UTC, aminoxix approved these changes
Great work - LGTM! 🚀

2022-10-21 15:55 UTC, merged

2022-10-21 18:27 UTC, Panquesito7 reviewed
Otherwise, everything looks great! Thanks. 🚀

2022-10-21 18:27 UTC, Panquesito7 commented on lang/scala.md
> +- Scala is a strong statically typed general-purpose programming language which supports both [object-oriented programming](https://en.wikipedia.org/wiki/Object-oriented_programming) and [functional
Not sure if we should use a list here (same for other parts of the document).