Add the C++ language
devstrons/heloworld pull request #41
Opened 2021-08-31 21:33 UTC by Panquesito7

Things added/changed:

- Add the C++ language to the list.

2021-09-03 23:36 UTC, Panquesito7 commented
@amino19, ping. Nobody is watching this repository. 👀

2021-09-04 06:37 UTC, amino19 commented
> @amino19, ping. Nobody is watching this repository. eyes

@Panquesito7: Actually we do, but working at back-end, also we consider `installation.md` in here! 
Confused?

2021-09-04 06:40 UTC, amino19 requested changes

2021-09-04 06:40 UTC, amino19 commented on lang/cpp.md
> +# C++ is the most powerful language!
```suggestion
# C++ is the most powerful language!
```
One has to write the whole installation process reg. Compiler, IDE, & extensions of VSC (Visual Studio Code), I am making one for reference, so give me some time.. : )

2021-09-10 22:15 UTC, Panquesito7 commented
Should I start working on this PR again, or is someone working on it? Thanks. 🙂

2021-09-10 22:40 UTC, amino19 commented
> Should I start working on this PR again, or is someone working on it? Thanks. slightly_smiling_face

Yes, obv! :slightly_smiling_face: 
Pl start contributing as it follows [here](https://github.com/devstrons/hello-world/blob/87c0b886b781edd21d053ee389a615895c48a013/lang/java.md).

2022-03-25 11:16 UTC, amino19 commented
@Panquesito7: I hope you're not forgotten about this Open Source Journey, emphasis on you isn't a good step because I believe you are already passionate about Open Source contributions, pl make it done, or assign anyone who completes this for you! :slightly_smiling_face:

2023-05-13 01:17 UTC, Panquesito7 commented
Working on this (sorry for the very very long delay).

2023-05-17 18:52 UTC, aminoxix approved these changes
LGTM! 🥳

2023-05-17 19:37 UTC, merged